version: '3'

networks:
  lerk-docker:
  lerk-dev:
  lerk-testing:

volumes:
  database-data:

services:
  database:
    image: 'postgres:9.6'
    env_file: .env.development
    networks:
      - lerk-dev
    ports:
      - 15432:5432
    volumes:
      - database-data:/var/lib/postgresql/data

  database-testing:
    image: 'postgres:9.6'
    env_file: .env.testing
    networks:
      - lerk-testing
    ports:
      - 25432:5432

  database-docker:
    image: 'postgres:9.6'
    env_file: .env.docker
    networks:
      - lerk-docker

  lerk-docker:
    image: 'lavode/lerk:latest'
    env_file: .env.docker
    networks:
      - lerk-docker
    command: bot

  web-docker:
    image: 'lavode/lerk:latest'
    env_file: .env.docker
    networks:
      - lerk-docker
    command: application
    ports:
      - 8080:8080
