version: '3'

networks:
  lerk-dev:

volumes:
  database-data:

services:
  database:
    image: 'postgres:9.6'
    env_file: .env
    networks:
      - lerk-dev
    ports:
      - 15432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
