# coding: utf-8

module Lerk
  module Config
    DISCORD_CLIENT_ID   = ENV.fetch('DISCORD_CLIENT_ID')
    DISCORD_TOKEN       = ENV.fetch('DISCORD_TOKEN')
    LERK_COMMAND_PREFIX = ENV.fetch('LERK_COMMAND_PREFIX', '!')
    STEAM_WEB_API_KEY   = ENV.fetch('STEAM_WEB_API_KEY', '')

    # Defaults to 2/s
    HIVE2_GLOBAL_RATE_LIMIT     = ENV.fetch('HIVE2_GLOBAL_RATE_LIMIT', 2).to_i
    HIVE2_GLOBAL_RATE_TIME_SPAN = ENV.fetch('HIVE2_GLOBAL_RATE_TIME_SPAN', 1).to_i

    # Defaults to 1/s
    HIVE2_USER_RATE_LIMIT     = ENV.fetch('HIVE2_USER_RATE_LIMIT', 1).to_i
    HIVE2_USER_RATE_TIME_SPAN = ENV.fetch('HIVE2_USER_RATE_TIME_SPAN', 1).to_i

    # Defaults to 1/5 min
    HIVE2_HELP_MESSAGE_RATE_LIMIT     = ENV.fetch('HIVE2_HELP_MESSAGE_RATE_LIMIT', 1).to_i
    HIVE2_HELP_MESSAGE_RATE_TIME_SPAN = ENV.fetch('HIVE2_HELP_MESSAGE_RATE_TIME_SPAN', 300).to_i

    EXCUSE_MAXIMUM_AMOUNT = ENV.fetch('EXCUSE_MAXIMUM_AMOUNT', 10).to_i
  end
end
